-- Unit and projectile classes in current FAF cache their army during creation.
-- Keeping the old global Entity wrapper would add an OnCreate call to every
-- simulation entity for a compatibility workaround that is no longer needed.
